spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/cakequake
    driver-class-name: org.postgresql.Driver
    username: cakeuser
    password: 12345678
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 2000