spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 50MB

  config:
    import: optional:file:external-db.yml

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT}/${DB_NAME}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER}
    password: ${DB_PASS}
    hikari:
      maximum-pool-size: 5   # ?? ??? ??
      minimum-idle: 2         # ?? ?? ??? ??
      idle-timeout: 30000     # ???? ?? ??? ???? ?? ?? (???)
      max-lifetime: 1800000   # ???? ?? ???? (???)
      connection-timeout: 2000 # ??? ?? ? ?? ?? ?? (???)

  #JPA Config
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        id:
          new_generator_mappings: true
  sql:
    init:
      mode: never

  #?? ??
  logging:
    level:
      com.cakequake: INFO
      org.springframework.security: TRACE

  output:
    ansi:
      enabled: ALWAYS

  com:
    cakequake:
      upload: upload

  jasypt:
    encryptor:
      password: ${JASYPT_ENCRYPTOR_PASSWORD}  # 환경 변수로부터 읽음

  pg:
    kakao:
      base-url: https://kapi.kakao.com
      admin-key: ${KAKAO_ADMIN_KEY}   # 환경 변수에서 읽어오는 카카오 Admin Key
      cid:       ${KAKAO_CID}         # 환경 변수에서 읽어오는 카카오 CID
    toss:
      base-url: https://api.tosspayments.com
      secret-key: ${TOSS_SECRET_KEY}   # 환경 변수에서 읽어오는 토스페이 Secret Key

  app:
    base-url: ${APP_BASE_URL}        # our-service(ngrok 혹은 실제 도메인)