spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 50MB

  config:
    import: optional:file:external-db.yml

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT}/${DB_NAME}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER}
    password: ${DB_PASS}
    hikari:
      maximum-pool-size: 5   # ?? ??? ??
      minimum-idle: 2         # ?? ?? ??? ??
      idle-timeout: 30000     # ???? ?? ??? ???? ?? ?? (???)
      max-lifetime: 1800000   # ???? ?? ???? (???)
      connection-timeout: 2000 # ??? ?? ? ?? ?? ?? (???)

  #JPA Config
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        id:
          new_generator_mappings: true
  sql:
    init:
      mode: never

  #?? ??
  logging:
    level:
      com.cakequake: INFO
      org.springframework.security: TRACE

  com:
    cakequake:
      upload: upload